apiVersion: batch/v1
kind: Job
metadata:
  name: sdk-integration
  namespace: v13-rapyuta-core
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: docker-registry.default.svc:5000/v13-rapyuta-core/sdk-integration-tests:latest
        env:
        - name: "RIO_CONFIG"
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
      volumes:
      - name: config
        configMap:
          name: sdk-config

