apiVersion: v1
kind: ConfigMap
metadata:
  name: sdk-config
  namespace: v13-rapyuta-core
data:
  config.json: >-
    {
      "catalog_host": "https://qacatalog.az39.rapyuta.io",
      "core_api_host": "https://qaapiserver.az39.rapyuta.io",
      "hwil_host": "https://hwil.rapyuta.io",
      "hwil_user": "ansible",
      "hwil_password": "HWIL_PASSWORD",
      "auth_token": "AUTH_TOKEN",
      "devices": [
        {
          "name":  "supervisord-arm32",
          "runtime": "Preinstalled",
          "ip": "10.91.1.14",
          "arch": "arm32v7",
          "distro": "kinetic"
        },
        {
          "name":  "docker-compose-arm32",
          "runtime": "Dockercompose",
          "ip": "10.91.1.15",
          "arch": "arm32v7",
          "distro": "kinetic"
        },
        {
          "name":  "docker-compose-amd64",
          "runtime": "Dockercompose",
          "ip": "10.4.3.207",
          "arch": "amd64",
          "distro": "melodic"
        }
      ],
      "git": {
         "ssh-key": "SSH_KEY"
      }
    }
