apiVersion: v1
kind: ConfigMap
metadata:
  name: sdk-config
  namespace: v13-rapyuta-core
data:
  config.json: >-
    {
      "catalog_host": "https://qacatalog.az39.rapyuta.io",
      "core_api_host": "https://qaapiserver.az39.rapyuta.io",
      "v2_api_host": "https://qaapi.rapyuta.io",
      "hwil_host": "https://hwil.rapyuta.io",
      "hwil_user": "ansible",
      "hwil_password": "HWIL_PASSWORD",
      "auth_token": "Bearer AUTH_TOKEN",
      "organization_guid": "org_guid",
      "devices": [
        {
          "name":  "docker-compose-amd64",
          "runtime": "Dockercompose",
          "ip": "10.4.3.207",
          "arch": "amd64",
          "distro": "melodic"
        }
      ],
    }
