name: Github Pages for Documentation
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Pipenv
        run: pip3 install pipenv

      - name: Install Dependencies
        run: pipenv install --categories docs

      - name: Build Documentation
        run: pipenv run python3 -m sphinx -M html docs/source docs/output

      - name: Deploy gh-pages
        if: github.repository == 'rapyuta-robotics/rapyuta-io-sdk' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/output/html
          cname: sdk.rapyuta.io
          force_orphan: true
