name: Upload to PyPi
on:
  release:
    types:
      - published

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          pip3 install pipenv twine
          pipenv install --dev

      - name: Upload Wheel
        run: |
          pipenv install setuptools
          pipenv run python setup.py bdist_wheel sdist
          twine upload \
            --repository ${{ secrets.TWINE_REPOSITORY }} \
            --non-interactive \
            --skip-existing \
            --verbose \
            dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_REPOSITORY: ${{ secrets.TWINE_REPOSITORY }}
