name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Run semantic-release
        run: |
          npm install --save-dev semantic-release@24.2.3
          npm install @semantic-release/git -D
          npm install @semantic-release/changelog -D
          npm install @semantic-release/exec -D
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

