name: Release
on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run semantic-release
        run: |
          npm install --save-dev semantic-release@19.0.2
          npm install @semantic-release/git -D
          npm install @semantic-release/changelog -D
          npm install @semantic-release/exec -D
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

